### ISSUE TITLE
Crash in landscape

### ISSUE THREAD

**Issue by ladyBeetleAlena** [jonathandarwin/edittext-inside-recyclerview#1]
Great idea! but, when, tried to repeat - the application crashes when switching to the landscape.  New created item row does not appear. Would you tell me, how i can fix it?

**Comment by jonathandarwin** [comment]
Thank you for your report! Can you provide the screenshot of the error message?

**Comment by ladyBeetleAlena** [comment]
> Thank you for your report! Can you provide the screenshot of the error message?

It is no crash app with error message, just new created item are not appearing after change screen orientation.

**Comment by jonathandarwin** [comment]
> > Thank you for your report! Can you provide the screenshot of the error message?
> 
> It is no crash app with error message, just new created item are not appearing after change screen orientation.

Hi! I'm really sorry for the late reply. I already fixed the issue. The issue is occur because I haven't write any handling code when configuration changes happen. The solution that I give is not the best, you can try using MVVM or at least using Parcelable instead of Serializable.
